In [3]:
import open3d as o3d
import numpy as np

# Load the .ply file
ply_file = "D:\GEO1101_Synthesisproject\Scaniverse_2024-09-12_131939.ply" #replace your .ply file path here 
pcd = o3d.io.read_point_cloud(ply_file)

# Print general point cloud info
print("Point cloud info:", pcd)

# Extract point coordinates
points = np.asarray(pcd.points)
print("Point coordinates:\n", points)

# Extract RGB colors if present
if pcd.has_colors():
    rgb_values = np.asarray(pcd.colors)
    print("RGB colors:\n", rgb_values)
else:
    print("No color information available.")

# Compute the mean of the points
mean = np.mean(points, axis=0)
print(f"Mean of the point cloud: {mean}")

# Compute the covariance matrix of the points
covariance_matrix = np.cov(points, rowvar=False)
print(f"Covariance Matrix:\n{covariance_matrix}")

# If you need normals (useful for geometric analysis)
pcd.estimate_normals()
normals = np.asarray(pcd.normals)
print("Normals:\n", normals)


Point cloud info: PointCloud with 753747 points.
Point coordinates:
 [[-24.28533554   5.66812515   8.59627724]
 [-24.28533554   5.60812473   8.59627724]
 [-24.28533554   5.54812527   8.59627724]
 ...
 [ 24.25466537   0.02812481  10.03627777]
 [ 24.27716446  -0.03187561  10.03627777]
 [ 24.30341339  -0.06562519  10.03627777]]
RGB colors:
 [[0.44705882 0.22745098 0.08627451]
 [0.4627451  0.24313725 0.08627451]
 [0.47843137 0.24313725 0.08627451]
 ...
 [0.32156863 0.25882353 0.24313725]
 [0.30588235 0.24313725 0.22745098]
 [0.30588235 0.24313725 0.21176471]]
Mean of the point cloud: [ 1.45983897 -1.00742515  7.63926703]
Covariance Matrix:
[[193.60333812  16.60946344   3.01078729]
 [ 16.60946344  30.79726831  -0.19788491]
 [  3.01078729  -0.19788491  13.9229967 ]]
Normals:
 [[ 0.74340476 -0.02284984  0.66845138]
 [ 0.83164456  0.04993439  0.55305865]
 [ 0.80309721 -0.00574558  0.59582032]
 ...
 [ 0.94731968  0.30436276 -0.09974331]
 [ 0.91624434  0.38866455 -0.09713999]
 [ 0.90456614  0.41

In [4]:
# Visualize the point cloud
o3d.visualization.draw_geometries([pcd])
